#+title: Readme

* Introduction

An Enhanced CLI for dolt.The official doltcli only provides git-like operations inside Dolt among the SQL tables,but not the files.So,to be more friendly,doltcli-ex provides commands to simplify the io operations and dolt operations.

** Commands

The ~scripts~ provides convenient Python scripts to add and remove data files in dolt. The installation will create executables automatically.

- ~doltadd~ :: Import the dataset file as SQL table or upload some kind of special files(README.md,LICENSE.md) in Dolt and then add it into Dolt's stage.

- ~doltrm~ :: Remove a table or some kind of special files in Dolt.



* Installation

** From pip

#+begin_src sh
pip install doltcli-ex
#+end_src

** From source

#+begin_src sh
pip install git+https://github.com/yuiant/doltcli-ex.git
#+end_src

* Contribution

** Formatting Code

To ensure the codebase complies with a style guide, please use [[https://github.com/PyCQA/flake8][flake8]], [[https://github.com/psf/black][black]] and [[https://github.com/PyCQA/isort][isort]] tools to format and check codebase for compliance with PEP8.
